# Generated by Django 5.2.7 on 2025-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(unique=True)),
                ('value', models.CharField(max_length=255)),
                ('prev_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=128)),
                ('block_hash', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('decided', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PREPREPARE', 'PREPREPARE'), ('PREPARE', 'PREPARE'), ('COMMIT', 'COMMIT')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('timestamp', models.FloatField()),
                ('signature', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('phase', 'value', 'sender')},
            },
        ),
    ]
